/*!CK:143869284!*//*1460391572,*/

if (self.CavalryLogger) { CavalryLogger.start_js(["k1fxX"]); }

__d('TypeaheadList',['fbt','AsyncRequest','CSS','DataStore','DOM','Event','Parent'],function a(b,c,d,e,f,g,h){if(c.__markCompiled)c.__markCompiled();function i(j,k,l,m,n,o){this.typeahead=j;this.list=k;this.subtitle=c('Parent').byTag(k,'td').firstChild;this.endpoint=l;this.inputName=m;this.added=o;this.count=k.childNodes.length;j.subscribe('select',function(p,q){this.handleSelect(q);}.bind(this));this.removeText=h._("Remove");Object.assign(this,n);c('Event').listen(k,'click',this.handleClick.bind(this));}Object.assign(i.prototype,{handleSelect:function(j){if(!(j.selected.uid in this.added)){this.updateCount(1);this.addItem(j);this.added[j.selected.uid]=true;}},handleClick:function(j){var k=c('Parent').byTag(j.getTarget(),'a'),l=k&&c('DataStore').get(k,'objectID');if(l){c('DOM').remove(c('Parent').byTag(k,'li'));delete this.added[l];this.save(l,true);this.updateCount(-1);}},addItem:function(j){var k=this.createItem(j),l=c('DOM').create('a',null,this.removeText);c('DataStore').set(l,'objectID',j.selected.uid);c('DOM').appendContent(k.firstChild,[' ',l]);c('DOM').appendContent(this.list,k);if(this.inputName){var m=c('DOM').create('input',{type:'hidden',value:j.selected.uid,name:this.inputName+'[]'});c('DOM').appendContent(k,m);}this.save(j.selected.uid);},createItem:function(j){return (c('DOM').create('li',null,c('DOM').create('div',{className:'fcb'},c('DOM').create('span',null,j.selected.text))));},updateCount:function(j){this.count+=j;c('CSS').conditionClass(this.subtitle,'hidden_elem',!!this.count);},save:function(j,k){if(!this.endpoint)return;new (c('AsyncRequest'))().setURI(this.endpoint).setData({objectID:j,remove:k}).send();}});f.exports=i;},null);
__d('legacy:typeahead-list',['TypeaheadList'],function a(b,c,d,e,f,g){if(c.__markCompiled)c.__markCompiled();b.TypeaheadList=c('TypeaheadList');},3);
__d("PrivacySettingsBlocking",[],function a(b,c,d,e,f,g){if(c.__markCompiled)c.__markCompiled();var h={setTypeaheadExclusions:function(i,j){i.getData().setExclusions(j);}};f.exports=h;},null);
__d("PrivacyUserBlockItem",[],function a(b,c,d,e,f,g){if(c.__markCompiled)c.__markCompiled();function h(i,j){"use strict";this.elem=j;this.uid_or_email=i;}f.exports=h;},null);
__d('PrivacyUserBlockList',['DOM','CSS','PrivacyUserBlockItem'],function a(b,c,d,e,f,g){if(c.__markCompiled)c.__markCompiled();function h(i,j){var k=arguments.length<=2||arguments[2]===undefined?null:arguments[2],l=arguments.length<=3||arguments[3]===undefined?null:arguments[3];'use strict';this.$PrivacyUserBlockList1=i;this.$PrivacyUserBlockList2=j.slice();this.$PrivacyUserBlockList3=k;this.$PrivacyUserBlockList4=l;this.$PrivacyUserBlockList5();}h.prototype.addBlockItem=function(i){'use strict';this.$PrivacyUserBlockList2.push(i);if(this.$PrivacyUserBlockList4!=null&&this.$PrivacyUserBlockList2.length>this.$PrivacyUserBlockList4)this.$PrivacyUserBlockList2.splice(0,this.$PrivacyUserBlockList2.length-this.$PrivacyUserBlockList4);this.$PrivacyUserBlockList5();};h.prototype.removeBlockItem=function(i){'use strict';var j=this.$PrivacyUserBlockList2.length;while(j--)if(this.$PrivacyUserBlockList2[j].uid_or_email==i)this.$PrivacyUserBlockList2.splice(j,1);this.$PrivacyUserBlockList5();};h.prototype.$PrivacyUserBlockList5=function(){'use strict';if(this.$PrivacyUserBlockList2.length>0){c('DOM').empty(this.$PrivacyUserBlockList1);this.$PrivacyUserBlockList2.forEach(function(i){return (c('DOM').appendContent(this.$PrivacyUserBlockList1,i.elem)&&c('CSS').show(i.elem));}.bind(this));if(this.$PrivacyUserBlockList3)c('CSS').hide(this.$PrivacyUserBlockList3);c('CSS').show(this.$PrivacyUserBlockList1);}else{c('CSS').hide(this.$PrivacyUserBlockList1);if(this.$PrivacyUserBlockList3)c('CSS').show(this.$PrivacyUserBlockList3);}};f.exports=h;},null);
__d('PrivacyUserBlockTracker',['DOM','CSS','DialogX','PrivacyUserBlockList','PrivacyUserBlockItem'],function a(b,c,d,e,f,g){if(c.__markCompiled)c.__markCompiled();var h={},i=[],j={addBlockList:function(k,l){h[k]=l;},blockUser:function(k,l,m){c('CSS').hide(m);c('DOM').appendContent(document.body,m);if(k in h)h[k].addBlockItem(l);j.hideAllDialogs();},unblockUser:function(k){for(var l in h)h[l].removeBlockItem(k);j.hideAllDialogs();},registerDialogToHideOnNextAction:function(k){i.push(k);},hideAllDialogs:function(){i.forEach(function(k){return k.hide();});}};f.exports=j;},null);